name: never_scene
channels:
  - pytorch
  - conda-forge
  - nvidia
  - https://software.repos.intel.com/python/conda/
  - defaults
dependencies:
  - python=3.10
  - brotli
  - certifi
  - cffi
  - click
  - cryptography
  - mkl
  - mpmath
  - networkx
  - pillow
  - requests
  - seaborn
  - tqdm
  - yaml
  - zipp
